CANNY_SIGMA_DEFAULT = 1.0
CANNY_LOW_THRESHOLD_DEFAULT = 0.1
CANNY_HIGH_THRESHOLD_DEFAULT = 0.95

NUMBER_OF_FRAMES = 720
FPS = 16

NUMBER_OF_EPICYCLES = 101
FOURIER_DT = 0.001

DO_SAMPLING = True
SAMPLING_SIZE = 1000

RANDOM_SEED = 0
